name: Publish multi-arch Docker images

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                base: [ 'debian:bullseye-20220125-slim', 'debian:buster-20220125-slim', 'ubuntu:focal-20220105' ]
                
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
        -
            name: Set Release Tag
            run: |
                date=$(date '+%Y-%m-%d')
                base="$(cut -d ':' -f2 <<< '${{ matrix.base }}')"
                base="$(cut -d '-' -f1 <<< ${base})"
                mpd_version=""
                distro_id=${base}
                if [ "${base}" = "bullseye" ]; then \
                    mpd_version="mpd-0.22.6-"; \
                fi
                if [ "${base}" = "buster" ]; then \
                    mpd_version="mpd-0.21.5-"; \
                fi
                if [ "${base}" = "focal" ]; then \
                    mpd_version="mpd-0.21.20"; \
                    distro_id="ubuntu-focal-"; \
                fi
                tags="${{secrets.DOCKER_USERNAME}}/mpd-base-image:${mpd_version}${distro_id},${{secrets.DOCKER_USERNAME}}/mpd-base-image:${mpd_version}${distro_id}-${date}"
                if [ "${base}" = "buster" ]; then \
                    echo "RELEASE_TAGS=${tags},${{secrets.DOCKER_USERNAME}}/mpd-base-image:${distro_id},${{secrets.DOCKER_USERNAME}}/mpd-base-image:stable"; \
                elif [ "${base}" = "bullseye" ]; then \
                    echo "RELEASE_TAGS=${tags},${{secrets.DOCKER_USERNAME}}/mpd-base-image:${distro_id},${{secrets.DOCKER_USERNAME}}/mpd-base-image:latest"; \
                elif [ "${base}" = "focal" ]; then \
                    echo "RELEASE_TAGS=${tags},${{secrets.DOCKER_USERNAME}}/mpd-base-image:${distro_id}"; \
                else \
                    echo "RELEASE_TAGS=${tags}"; \
                fi \
                >> $GITHUB_ENV
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1
            with:
                platforms: all
        -
            name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
        -
            name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        -
            name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: .
                build-args: |
                    BASE_IMAGE=${{ matrix.base }}
                platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
                push: true
                tags: ${{ env.RELEASE_TAGS }}
